mysite/urls.py
from django.contrib import admin
from django.urls import include, path

# 여기서 정의하는 polls는 polls파일안에 모든내용이 polls안써도 urls부터 시작함!
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'pollss'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),

    # ex: /polls/5/
    # index.html에서 /polls/1또는 2를 받고오면! view파일에 있는detail 함수실행!
    path('<int:question_id>/', views.detail, name='detail'),


    # question.id arg로 받지만 주소에서는 . 대신 _ 를 사용하여 이어준다!
    # ex: /polls/5/results/
    path('<int:question_id>/resultshaha/', views.results, name='results'),

    # detail.html에서 여기로 오게 된다! 즉 view.vote를 보자!
    # 왜 <int:question_id>/vote/는 안나오냐면 vote에서
    # reverse로 바로 주소값을 result로 준다!
    # 주소창에 실험해본다고 polls/2/vote해도 안됨 어짜피.. 왜냐하면 post방식이라
    # url로 choice값이 들어오지 않음.. 그래서 null이라 오류남!
    # ex: /polls/5/vote/
    path('<int:question_id>/vote22aaa/', views.vote2233, name='vote2277'),
]  # 패스뒤에 붙는건 vote22aaa // resultshaha 내맘임.. 결과에 영향 안미침
# 중요한건 탬플릿이나 뷰에서 app_name:name 과 views안에있는 함수이름임!!

polls/models.py
from django.db import models
import datetime


#  모델에서 양식을 정의하고 migrations에서 정의한것을 admin파일에 어떻게 보낼건지 결정!
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    # data published 이름을 가질것임 만들어진 날짜에!

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        # 최근에 만들어졌는지 아닌지... 만들어진날짜가 더크면.. 뭐보다?
        # 현재시간에서 하루 뺀거 보다! 즉 어제만들어진것보다 최근이면 true


class Choice(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE)  # 질문을 포린키로 받는다!
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.template import loader
from django.urls import reverse
from django.shortcuts import get_object_or_404, render

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # 0~5까지 불러오는데 pub_date 이면 만든지 오래된거부터 -pub_date 이면 최근거 부터!
    print("A")
    print(latest_question_list)
    # Question은 결국 QuerySet을 반환한다!
    print("B")  # pipenv shell에서 콘솔 확인가능!
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', {'latest_question_list__': latest_question_list})
    # context를 넣어도 되고 직접 넣어도됨!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # latest_question_list__ 을 index.html로 보내줌!

# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)


# /polls/1또는 2를 받고 url에서 주소타고 view.detail이 실행되면!
# 1또는 2가 아이디로 question_id적용되서 들어간다!
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # model의 Question을 가서 pk를이용해 row를 가져온다!
    # get_object_or_404 이미정의된 함수이다! import했음..
    # 값이 있으면 가져오고 없으면 404에러를 일으킨다!
    print(question)
    return render(request, 'polls/detail.html', {'question': question})
    # 여기서 다시 탬플릿 파일안에 polls 속의 detail.html을 실행할것임!


def vote2233(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        # detail의 choice의 value 값이 post에 들어감
        # post를 request해서 choice된값을 pk에 넣겠음!
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('pollss:results', args=(question.id,)))
        # reverse는 args 형식으로 넘겨줘야한다!
        # reverse는 appname : urls'name으로 화면을 열고
        # render은 바로 html형식을 연다!
        # 왜 <int:question_id>/vote/는 안나오냐면 reverse로 바로 주소값을 result로 준다!


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<h1>{{ question.pub_date }}</h1>
{% comment %} question에는 위 두개의 자료를 들고있음! 
    밑에는 question이 없다면 에러를 일으킴!
{% endcomment %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pollss:vote2277' question.id %}" method="post">
  {% csrf_token %}
  {% comment %}  csrf_token 는 털림(보안) 방지이다! {% endcomment %}
  {% for choice in question.choice_set.all %}
  {% comment %} _set을 쓰는경우는 일대 다에서.. 일이 포린키된쪽에서 가져올때 넣어야함!
    즉 문제는 하나고 choice는 여러개인데 하나에서 여러개를 가져올때!(포린키 빌려줬으니)
   {% endcomment %}
   {% comment %} forloop.counter 는 루프돌때마다 하나하나씩 알아서 번호줌.. 
   i = i+1와같은 존재 {% endcomment %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}{{ choice.votes }}</label><br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list__ %}
<ul>
  {% for question in latest_question_list__ %}
  {% comment %} latest_qu~~~의 객체 하나하나를 question에 넣겠음! {% endcomment %}
  <li><a href="{% url 'pollss:detail' question.id %}">{{ question.question_text }}</a></li>
  {% endfor %}
  {% comment %} pollss는 polls파일의 url 앱이름이다! 
  즉 앱이름 + path name해서 polls:detail이 되는것임!
  {% endcomment %}
  {% comment %} 링크를 만드는데 question마다 아이디를 타고 가겠음! {% endcomment %}
  {% comment %} 주소는 url에서 볼수있다! <int:question.id>이렇게! {% endcomment %}
  {% comment %} http://localhost:8000/polls/2/ 이런식! {% endcomment %}
  {% comment %} 링크를 누르게되면 다시 polls의 url로 가서 확인해보자! {% endcomment %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% comment %} choice.votes가 복수면 s를 더 해줄것이다! {% endcomment %}
  {% endfor %}
</ul>

<a href="{% url 'pollss:detail' question.id %}">Vote again?</a>